AddressBookWebApp/Models/AddressBook.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AddressBookWebApp.Models
{
    public class AddressBook
    {
        [Key]
        public int AddressBookId { get; set; }

        [DisplayName("First Name")]
        [Required]
        public string FirstName { get; set; }

        [DisplayName("Middle Name")]
        public string? MiddleName { get; set; }

        [DisplayName("Last Name")]
        [Required]
        public string LastName { get; set; }

        [DisplayName("Address Line")]
        [Required]
        public string AddressLine { get; set; }
        
        [Required]
        public string City { get; set; }
        
        [Required]
        public string Province { get; set; }

        [DisplayName("Phone Number")]
        [Required]
        public string PhoneNumber { get; set; }

        [NotMapped]
        public string FullName
        {
            get { 
                if (MiddleName != null)
                {
                    return FirstName + " " + MiddleName + " " + LastName;
                }
                
                return FirstName + " " + LastName; 
            }
        }
    }
}

AddressBookWebApp/Controllers/AddressBookController.cs
using AddressBookWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace AddressBookWebApp.Controllers
{
    public class AddressBookController : Controller
    {
        private readonly AddressBookDataAccess _abda;

        public AddressBookController(AddressBookDataAccess abda)
        {
            _abda = abda;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<AddressBook> ab = new List<AddressBook>();
            try
            {
                ab = _abda.GetAllPersons();
            }
            catch (Exception ex)
            {

                TempData["errorMessage"] = ex.Message;
            }
            return View(ab);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(AddressBook ab)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TempData["errorMessage"] = "Object data is not valid!";
                }
                bool result = _abda.Insert(ab);

                if (!result)
                {
                    TempData["errorMessage"] = "Unable to insert person";
                    return View();
                }

                TempData["successMessage"] = "Person data has been successfully added to the address book!";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            try
            {
                AddressBook ab = _abda.GetPersonById(id);
                if (ab.AddressBookId == 0)
                {
                    TempData["errorMessage"] = $"No data found with an Id: {id}";
                    return RedirectToAction("Index");
                }
                return View(ab);
            }
            catch (Exception ex)
            {

                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }

        [HttpPost]
        public IActionResult Edit(AddressBook ab)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TempData["errorMessage"] = "Model data is invalid";
                    return View();
                }
                bool result = _abda.Update(ab);

                if (!result)
                {
                    TempData["errorMessage"] = "Unable to update person data";
                    return View();
                }
                TempData["successMessage"] = "Person data has been updated successfully!";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            try
            {
                AddressBook ab = _abda.GetPersonById(id);
                if (ab.AddressBookId == 0)
                {
                    TempData["errorMessage"] = $"No data found with an Id: {id}";
                    return RedirectToAction("Index");
                }
                return View(ab);
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(AddressBook ab)
        {
            try
            {
                bool result = _abda.Delete(ab.AddressBookId);

                if (!result)
                {
                    TempData["errorMessage"] = "Unable to delete person data";
                    return View();
                }
                TempData["successMessage"] = "Person data has been deleted successfully!";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }
    }
}

AddressBookWebApp/Views/AddressBook/Add.cshtml
@model AddressBookWebApp.Models.AddressBook
@{
    ViewData["Title"] = "Add New Person to Address Book";
}

<div class="container-form">
    <h3>@ViewData["Title"]?.ToString()</h3>
    <hr />
    <form method="post" action="Add" class="form-control mt-3" autocomplete="off">
        <div class="mb-3">
            <label class="form-label" asp-for="FirstName"></label>
            <input type="text" class="form-control" asp-for="FirstName" placeholder="Enter first name" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="MiddleName"></label>
            <input type="text" class="form-control" asp-for="MiddleName" placeholder="Enter middle name" />
            <span asp-validation-for="MiddleName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="LastName"></label>
            <input type="text" class="form-control" asp-for="LastName" placeholder="Enter last name" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label class="form-label" asp-for="AddressLine"></label>
            <input type="text" class="form-control" asp-for="AddressLine" placeholder="Enter address line" />
            <span asp-validation-for="AddressLine" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="City"></label>
            <input type="text" class="form-control" asp-for="City" placeholder="Enter city" />
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="Province"></label>
            <input type="text" class="form-control" asp-for="Province" placeholder="Enter province" />
            <span asp-validation-for="Province" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="PhoneNumber"></label>
            <input type="text" class="form-control" asp-for="PhoneNumber" placeholder="Enter phone number" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <div class="btn-group col-lg-12">
                <button type="submit" class="btn btn-success">Add</button>
                <a asp-controller="AddressBook" asp-action="Index" class="btn btn-dark" style="width: 150px;">Back to list</a>
            </div>
        </div>
    </form>
</div>

@section Scripts
    {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AddressBookWebApp/Views/AddressBook/Delete.cshtml
@model AddressBookWebApp.Models.AddressBook
@{
    ViewData["Title"] = "Delete Person Data";
}

<div class="container-form">
    <h3>@ViewData["Title"]?.ToString()</h3>
    <hr />

    <form method="post" action="Delete" class="form-control mt-3" autocomplete="off">
        <div class="mb-3">
            <label class="form-label" asp-for="AddressBookId"></label>
            <input type="text" class="form-control" asp-for="AddressBookId" readonly />
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="FirstName"></label>
            <input type="text" class="form-control" asp-for="FirstName" readonly />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="MiddleName"></label>
            <input type="text" class="form-control" asp-for="MiddleName" readonly />
            <span asp-validation-for="MiddleName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="LastName"></label>
            <input type="text" class="form-control" asp-for="LastName" readonly />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="AddressLine"></label>
            <input type="text" class="form-control" asp-for="AddressLine" readonly />
            <span asp-validation-for="AddressLine" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="City"></label>
            <input type="text" class="form-control" asp-for="City" readonly />
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="Province"></label>
            <input type="text" class="form-control" asp-for="Province" readonly />
            <span asp-validation-for="Province" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="PhoneNumber"></label>
            <input type="text" class="form-control" asp-for="PhoneNumber" readonly />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div>
            <div class="btn-group col-lg-12">
                <button type="submit" class="btn btn-danger">Delete</button>
                <a asp-controller="AddressBook" asp-action="Index" class="btn btn-dark" style="width: 150px;">Back to list</a>
            </div>
        </div>
    </form>
</div>

@section Scripts
    {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AddressBookWebApp/Views/AddressBook/Edit.cshtml
@model AddressBookWebApp.Models.AddressBook
@{
    ViewData["Title"] = "Update Person Data";
}

<div class="container-form">
    <h3>@ViewData["Title"]?.ToString()</h3>
    <hr />

    <form method="post" action="Edit" class="form-control mt-3" autocomplete="off">
        <div class="mb-3">
            <label class="form-label" asp-for="AddressBookId"></label>
            <input type="text" class="form-control" asp-for="AddressBookId" readonly />
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="FirstName"></label>
            <input type="text" class="form-control" asp-for="FirstName" placeholder="Enter first name" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="MiddleName"></label>
            <input type="text" class="form-control" asp-for="MiddleName" placeholder="Enter middle name" />
            <span asp-validation-for="MiddleName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="LastName"></label>
            <input type="text" class="form-control" asp-for="LastName" placeholder="Enter last name" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="AddressLine"></label>
            <input type="text" class="form-control" asp-for="AddressLine" placeholder="Enter address line" />
            <span asp-validation-for="AddressLine" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="City"></label>
            <input type="text" class="form-control" asp-for="City" placeholder="Enter city" />
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="Province"></label>
            <input type="text" class="form-control" asp-for="Province" placeholder="Enter province" />
            <span asp-validation-for="Province" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="PhoneNumber"></label>
            <input type="text" class="form-control" asp-for="PhoneNumber" placeholder="Enter phone number" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <div class="btn-group col-lg-12">
                <button type="submit" class="btn btn-success">Update</button>
                <a asp-controller="AddressBook" asp-action="Index" class="btn btn-dark" style="width: 150px;">Back to list</a>
            </div>
        </div>
    </form>
</div>

@section Scripts
    {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AddressBookWebApp/Views/AddressBook/Index.cshtml
@model IEnumerable<AddressBookWebApp.Models.AddressBook>

@{
    ViewData["Title"] = "Address Book List";
}

<h3 class="my-2">
    @ViewData["Title"]
</h3>
<hr />

<form>
    <div class="input-group">
        <input id="searchBar" type="text" onkeyup="searchName()" class="form-control" placeholder="Search address book">
    </div>
    <table id="addressTable" class="table table-responsive table-hover table-bordered">
        <thead>
            <tr class="table-active">
                <th>Address Book Id</th>
                <th>Full Name</th>
                <th>Address Line</th>
                <th>City</th>
                <th>Province</th>
                <th>Phone Number</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                @foreach (var address in Model)
                {
                    <tr>
                        <td>@address.AddressBookId</td>
                        <td>@address.FullName</td>
                        <td>@address.AddressLine</td>
                        <td>@address.City</td>
                        <td>@address.Province</td>
                        <td>@address.PhoneNumber</td>
                        <td>
                            <div class="btn btn-group">
                                <a asp-controller="AddressBook" asp-action="Edit" asp-route-id="@address.AddressBookId" class="btn btn-success">Update</a>
                                <a asp-controller="AddressBook" asp-action="Delete" asp-route-id="@address.AddressBookId" class="btn btn-danger">Delete</a>
                            </div>
                        </td>

                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="6" class="text-center">
                        <div>
                            Data is currently unavailable.
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <button asp-controller="AddressBook" asp-action="Add" class="btn btn-primary">Add New Data To Address Book</button>
</form>

<script>
    function searchName() {
        // Declare variables
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("searchBar");
        filter = input.value.toUpperCase();
        table = document.getElementById("addressTable");
        tr = table.getElementsByTagName("tr");

        // Loop through all table rows, and hide those who don't match the search query
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[1];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
</script>